# Generated by Django 2.1.3 on 2019-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('ordinal_column', models.IntegerField(primary_key=True, serialize=False)),
                ('name_column', models.CharField(max_length=50)),
                ('width_column', models.IntegerField(default=1)),
            ],
        ),
    ]
