# Generated by Django 2.1.3 on 2019-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepath',
            name='file_obj',
            field=models.FilePathField(path=None),
        ),
    ]
