# Generated by Django 2.1.3 on 2019-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20190416_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filepath',
            name='file_obj',
            field=models.FilePathField(path='C:\\Users\\rk0f\\Documents\\GitHub\\dj-homeworks\\creating-project\\application'),
        ),
    ]
